<?php

namespace App\Constants;

class OrdersStatus
{
    const CONTRACT_SIGNED_EXPORTER = 1;
    const CONTRACT_SIGNED_IMPORTER = 2;
    const FIRST_TERM_PAYMENT_SUBMITTED = 3;
    const FIRST_TERM_PAYMENT_RECEIVED = 4;
    const PRODUCT_IN_PRODUCTION = 5;
    const PRODUCTION_COMPLETED = 6;
    const TEST_LAB_SENT = 7;
    const SECOND_TERM_PAYMENT_SUBMITTED = 8;
    const SECOND_TERM_PAYMENT_RECEIVED = 9;
    const FREIGHT_DOCUMENTS_SENT = 10;
    const THIRD_TERM_PAYMENT_SUBMITTED = 11;
    const THIRD_TERM_PAYMENT_RECEIVED = 12;
    const BILL_OF_LADING_SENT = 13;
    const PRODUCT_SAFELY_ARRIVED = 14;
    const TRANSACTION_COMPLETED = 15;
}
